### ISSUE TITLE
page.html: à quoi sert la variable pagination de la front-matter

### ISSUE THREAD

**Issue by yann-yinn** [fireblogcms/eleventy-starter-fireblog#9]
Si je change le paramètre "size" ci-dessous, ça n'a pas d'effet.

```
layout: default
pagination:
    data: data.posts
    size: 2
    alias: posts
permalink: "post/{{ posts.slug }}/"
```

Par ailleurs la pagination semble plutôt provenir de `data.js`, ligne 46: 

`posts(last: 20, before: "${before}"){`
